### ISSUE TITLE
too laggy

### ISSUE THREAD

**Issue by alpamys-qanybet** [JanPeter/RN-NavigationHeaderAnimation#2]
I implemented your code on android real device, but it is working too laggy

**Comment by JanPeter** [comment]
What phone and Android version are you using?

I‘m afraid that I won‘t be able to help you on this one, because this is already one of the better ways of doing this kind of animation and I‘m already using native events/animations. So I think that this is actually the fastest way of animating this :/

**Comment by alpamys-qanybet** [comment]
@JanPeter, meizu m5 note, Android 6.0

**Comment by JanPeter** [comment]
As I mentioned before, I don't think that I'm able to help you with that issue.

Have you tried bundling the app as a production version?
You can test it with this command:
```
react-native run-android --variant=release
```
